name: Build ImmortalWrt AX6000

on:
  workflow_dispatch:
  push:
    branches: [ ax6000-bonding ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential clang flex bison g++ gawk gcc-multilib \
            g++-multilib gettext git libncurses5-dev libssl-dev python3-distutils rsync unzip zlib1g-dev \
            file wget curl ccache asciidoc libzstd-dev

      - name: Update feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Apply diffconfig
        run: |
          [ -f seed/diffconfig ] && cat seed/diffconfig >> .config
          make defconfig

      - name: Build firmware
        run: |
          make -j$(nproc) || make -j1 V=s

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: AX6000-firmware
          path: |
            bin/targets/**/*.bin
            bin/targets/**/*.manifest
            bin/packages/**/*
